### ISSUE TITLE
scores parameter of cityiograph.City unclear

### ISSUE THREAD

**Issue by kalyons11** [mitmedialab/CityMatrixSim#20]
This parameter can cause issues when sent to JSON, as sometimes the order of the list values in `city.scores` does not match the same order of the keys in `city.metrics`.

As I see it, there are **2** solutions for this issue.

1. Remove the `scores` parameter altogether. We know it can be quickly calculated, as it is done here:

```
scores = [ weight * fun(city) for name, fun, weight in self.metrics ]
```

2. Change `city.scores` to be a `dict` mapping metric key -> weighted score value. This way, you never lose clarity in which score value matches up to which key. This may also come into play when it comes time to **visualize scores** in the GH client.

**Comment by popabczhang** [comment]
Agreed. 
I will prefer solution 2, because Unity and GH client need it to visualize the scores. 
I will edit the GH CV client to send the JSON format as you suggested: 
{"grid":[...],"objects":{...,"scores":{"density":0,"diversity":0,"energy":0,"traffic":0,"solar":0}}}
Alex once pointed out that the values of these scores should not be multiplied by the AI Weight, but the original scores calculate the from the city. Because when you visualize them in GH and Unity client, you don't want the radar chart to show zero scores when the AI Weights are put to zero by the users.

**Comment by popabczhang** [comment]
Question: will the order issue happen on the following lists in JSON? 
	"densities": [1, 1, 1, 1, 1, 1],
	"AIWeights": [0.2, 0.2, 0.2, 0.2, 0.2],
	"AIMov": ["CELL", 0, 0, 0],

**Comment by kalyons11** [comment]
1. Then what makes this `scores` parameter any different from the `metrics` dictionary if we are not multiplying by the respective weights?

2. I don't believe those other lists, like `densities`, `AIWeights` and `AIMov` are inverted. We haven't had any issues in the past with density indices changing. I just saw that in a few of the example predicted cities, the scores and metrics did not match up numerically element-wise.

**Comment by popabczhang** [comment]
![image](https://user-images.githubusercontent.com/2801912/27805617-bc16cc5a-6003-11e7-84d8-5ae797b45a0d.png)
![image 1](https://user-images.githubusercontent.com/2801912/27805618-be009fd2-6003-11e7-9736-e30e327174f5.png)

**Comment by popabczhang** [comment]
JSON format update: 
![metrics json format](https://user-images.githubusercontent.com/2801912/27812737-21b93e40-603f-11e7-95f7-b67048d39fea.PNG)
